# Netlify settings
[build]
  base    = "web"
  publish = "web/public"
  command = "git lfs fetch && yarn --ignore-engines --ignore-optional --non-interactive && node_modules/.bin/webpack -p --mode=production && hugo"

[context.production.environment]
  HUGO_VERSION = "0.41"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.41"
