set(CTEST_CMAKE_GENERATOR "Ninja")
set(CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/../..")
set(CTEST_BINARY_DIRECTORY "${CTEST_SOURCE_DIRECTORY}/build-cdash")

ctest_empty_binary_directory("${CTEST_BINARY_DIRECTORY}")
